name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
    #- name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    #    python-version: 3.9
    - name: Install dependencies
      #env:
      #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  LOG_LEVEL: 1
      #  LOG_FILE: log_file.log
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
